# This file was generated by GoReleaser. DO NOT EDIT.
cask "cat-switch" do
  app "CatSwitch.app"
  # Only :sonoma(.14) and above is supported.
  depends_on macos: :sonoma

  version "0.2.0-rc.3"

  on_macos do
    on_intel do
      sha256 "e40686004b82bf8f1a8dbce8c3a7c60c66cd095e260f17e36ded72768d5dab3a"
      url "https://github.com/aki-s/CatSwitch-dist/releases/download/#{version}/CatSwitch_#{version}_x86_64.zip"
    end
    on_arm do
      sha256 "d464e0783e1d88c1890feed56aa1aac4fbd475081d4f654e4f93687c42de06c9"
      url "https://github.com/aki-s/CatSwitch-dist/releases/download/#{version}/CatSwitch_#{version}_arm64.zip"
    end
  end

  name "cat-switch"
  desc "Categorical Application Switcher"
  homepage "https://github.com/aki-s/CatSwitch-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "CatSwitch.app/Contents/MacOS/CatSwitch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/CatSwitch.app"]
    end
  end

  uninstall quit: [
      "com.aki-s.cat-switch",
      "com.aki-s.cat-switch",
    ]

  zap trash: [
      "~/Library/Application Support/CatSwitch",
      "~/Library/Caches/com.aki-s.cat-switch",
      "~/Library/Logs/CatSwitch/",
      "~/Library/Preferences/com.aki-s.cat-switch.plist",
    ]

end
