# This file was generated by GoReleaser. DO NOT EDIT.
cask "cat-switch" do
  app "CatSwitch.app"
  # Only :sonoma(.14) and above is supported.
  depends_on macos: :sonoma
  binary "#{appdir}/CatSwitch.app/Contents/MacOS/CatSwitch", target: "cat-switch"

  version "0.2.0-rc.1"

  on_macos do
    on_intel do
      sha256 "08ab9cbb3a7957785c8533f209ae6a1e5c889701d6839b81cc04a19b69dba79e"
      url "https://github.com/aki-s/CatSwitch-dist/releases/download/#{version}/CatSwitch_#{version}_x86_64.zip"
    end
    on_arm do
      sha256 "3fa301bdb67cf60e12af3ba15b73fe589457d0a0cbb2c9709ca5103c3be30972"
      url "https://github.com/aki-s/CatSwitch-dist/releases/download/#{version}/CatSwitch_#{version}_arm64.zip"
    end
  end

  name "cat-switch"
  desc "Categorical Application Switcher"
  homepage "https://github.com/aki-s/CatSwitch-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "#{appdir}/CatSwitch.app/Contents/MacOS/CatSwitch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/CatSwitch.app"]
      system_command "/usr/bin/open", args: ["#{appdir}/CatSwitch.app"]
    end
  end

  uninstall quit: [
      "com.aki-s.cat-switch",
      "com.aki-s.cat-switch",
    ],
    trash: [
      "/Applications/CatSwitch.app",
    ]

  zap trash: [
      "~/Library/Application Support/CatSwitch",
      "~/Library/Caches/com.aki-s.cat-switch",
      "~/Library/Logs/CatSwitch/",
      "~/Library/Preferences/com.aki-s.cat-switch.plist",
    ]

end
