# This file was generated by GoReleaser. DO NOT EDIT.
cask "cat-switch" do
  app "CatSwitch.app"

  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "28d933e2d5cdfc05327f59378fdb834f6f31d32227ed7369315d0bcbf6434c09"
      url "https://github.com/aki-s/CatSwitch-dist/releases/download/#{version}/CatSwitch_#{version}_x86_64.zip"
    end
    on_arm do
      sha256 "142d9410bf57dcae6494057afe5526d9d2cd8f9081019271fe12cef62eaee0ab"
      url "https://github.com/aki-s/CatSwitch-dist/releases/download/#{version}/CatSwitch_#{version}_arm64.zip"
    end
  end

  name "cat-switch"
  desc "Categorical Application Switcher for macOS"
  homepage "https://github.com/aki-s/CatSwitch-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cat-switch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/CatSwitch.app"]
    end
  end

  uninstall quit: [
      "com.aki-s.cat-switch",
    ]

  zap trash: [
      "~/Library/Logs/CatSwitch/",
      "~/Library/Application Support/CatSwitch",
      "~/Library/Caches/com.aki-s.cat-switch",
      "~/Library/Preferences/com.aki-s.cat-switch.plist",
    ]

end
