# This file was generated by GoReleaser. DO NOT EDIT.
cask "win-pin" do
  app "WinPin.app"
  # Only :ventura(.13) and above is supported.
  depends_on macos: :ventura
  binary "#{appdir}/WinPin.app/Contents/MacOS/WinPin", target: "win-pin"

  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "ef2107a0306854007b8c1d37af6b238c8e820c337d13de468ba097a39fca4c1f"
      url "https://github.com/aki-s/WinPin/releases/download/#{version}/WinPin_#{version}_x86_64.zip"
    end
    on_arm do
      sha256 "a8e3f1e04389544f1725e17a75842562af181dc6fafc499b3e4427ac04b7bb4f"
      url "https://github.com/aki-s/WinPin/releases/download/#{version}/WinPin_#{version}_arm64.zip"
    end
  end

  name "win-pin"
  desc "Per-window pinning menu bar application"
  homepage "https://github.com/aki-s/WinPin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "#{appdir}/WinPin.app/Contents/MacOS/WinPin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/WinPin.app"]
      system_command "/usr/bin/open", args: ["#{appdir}/WinPin.app"]
    end
  end

  uninstall quit: [
      "com.akis.WinPin",
      "com.akis.WinPin",
    ],
    trash: [
      "/Applications/WinPin.app",
    ]

  zap trash: [
      "~/Library/Application Support/WinPin",
      "~/Library/Caches/com.akis.WinPin",
      "~/Library/Logs/WinPin/",
      "~/Library/Preferences/com.akis.WinPin.plist",
    ]

end
