# This file was generated by GoReleaser. DO NOT EDIT.
cask "win-pin" do
  app "WinPin.app"
  # Only :ventura(.13) and above is supported.
  depends_on macos: :ventura
  binary "#{appdir}/WinPin.app/Contents/MacOS/WinPin", target: "win-pin"

  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "b8f1fd2fb87c7502a862fcc3b143e088c08b8f8a84390d14c426d556f18b9dc6"
      url "https://github.com/aki-s/WinPin/releases/download/#{version}/WinPin_#{version}_x86_64.zip"
    end
    on_arm do
      sha256 "9efa58162fcaab253d32aca31e41e5f1617ad533d8d214e5d6b2cfb5cedf7ea1"
      url "https://github.com/aki-s/WinPin/releases/download/#{version}/WinPin_#{version}_arm64.zip"
    end
  end

  name "win-pin"
  desc "Per-window pinning menu bar application"
  homepage "https://github.com/aki-s/WinPin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "#{appdir}/WinPin.app/Contents/MacOS/WinPin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/WinPin.app"]
      system_command "/usr/bin/open", args: ["#{appdir}/WinPin.app"]
    end
  end

  uninstall quit: [
      "com.akis.WinPin",
      "com.akis.WinPin",
    ],
    trash: [
      "/Applications/WinPin.app",
    ]

  zap trash: [
      "~/Library/Application Support/WinPin",
      "~/Library/Caches/com.akis.WinPin",
      "~/Library/Logs/WinPin/",
      "~/Library/Preferences/com.akis.WinPin.plist",
    ]

end
