# This file was generated by GoReleaser. DO NOT EDIT.
cask "win-pin" do
  app "WinPin.app"
  # Only :ventura(.13) and above is supported.
  depends_on macos: ">= :ventura"
  binary "#{appdir}/WinPin.app/Contents/MacOS/WinPin", target: "win-pin"

  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "2050718416fb89232bcdf096ecb26b810dba3d07cce6cf51e4fda1fcc0633be1"
      url "https://github.com/aki-s/WinPin/releases/download/#{version}/WinPin_#{version}_x86_64.zip"
    end
    on_arm do
      sha256 "d4eb8c3e937ba440f299465159ed87bab2631b0aaf1e04c8c33e43bd88f62e58"
      url "https://github.com/aki-s/WinPin/releases/download/#{version}/WinPin_#{version}_arm64.zip"
    end
  end

  name "win-pin"
  desc "Per-window pinning menu bar application"
  homepage "https://github.com/aki-s/WinPin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "#{appdir}/WinPin.app/Contents/MacOS/WinPin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/WinPin.app"]
      system_command "/usr/bin/open", args: ["#{appdir}/WinPin.app"]
    end
  end

  uninstall quit: [
      "com.akis.WinPin",
      "com.akis.WinPin",
    ],
    trash: [
      "/Applications/WinPin.app",
    ]

  zap trash: [
      "~/Library/Application Support/WinPin",
      "~/Library/Caches/com.akis.WinPin",
      "~/Library/Logs/WinPin/",
      "~/Library/Preferences/com.akis.WinPin.plist",
    ]

end
